language: php

sudo: true

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
matrix:
  allow_failures:
    - php : nightly

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys

script:
  - if [[$(phpenv version-name) >= "7.2" ]]; then composer install:quality-tools; fi
  - if [[$(phpenv version-name) >= "7.2" ]]; then composer test:quality-tools; fi
  - eval $(./algolia-keys export)
  - composer test
