language: php

sudo: true

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

  allow_failures:
    - php: nightly

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

before_script:
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys
  - eval $(./algolia-keys export)

script:
  - if [[ ${TRAVIS_PHP_VERSION} >= "7.2" ]]; then composer test:install; composer test:phpstan; fi
  - composer test
