language: php

sudo: true

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

  allow_failures:
    - php: nightly

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

before_script:
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys
  - eval $(./algolia-keys export)

script:
  - if [[$(phpenv version-name) >= "7.2" ]]; then composer install:test; fi
  - if [[$(phpenv version-name) >= "7.2" ]]; then composer phpstan:test; fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [[ ! "$TRAVIS_PULL_REQUEST_SLUG" =~ ^algolia\/ ]]; then eval $(./algolia-keys export) && composer test; else composer test; fi
