language: php

sudo: true

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

allow_failures:
  - php: nightly

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

before_script:
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys
  
script:
  - vendor/bin/php-cs-fixer fix -v --dry-run
