language: php

sudo: true

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

  allow_failures:
    - php: nightly


install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

before_script:
  - wget https://alg.li/algolia-keys && chmod +x algolia-keys
  
script:
  - $(./algolia-keys export)
  - php vendor/bin/phpunit -v --testsuite Integration
  - vendor/bin/php-cs-fixer fix -v --dry-run
